"""Shared domain models for ingestion, OKF, retrieval, and agent outputs."""

from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field


class DocumentChunk(BaseModel):
    """Normalized text chunk generated during ingestion."""

    doc_id: str
    source_path: Path
    section: str = "root"
    text: str
    chunk_id: str
    checksum: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ExtractedConcept(BaseModel):
    """Concept object produced by extraction stage."""

    concept_id: str
    concept_type: str
    title: str
    description: str
    tags: list[str] = Field(default_factory=list)
    resource: str | None = None
    owners: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)
    aliases: list[str] = Field(default_factory=list)
    evidence_chunk_ids: list[str] = Field(default_factory=list)


class ConceptFrontmatter(BaseModel):
    """YAML frontmatter contract for OKF concept files."""

    type: str
    title: str
    description: str
    tags: list[str] = Field(default_factory=list)
    resource: str | None = None
    timestamp: str


class ConceptDocument(BaseModel):
    """Represents one OKF concept markdown file."""

    concept_id: str
    relative_path: str
    frontmatter: ConceptFrontmatter
    body: str
    links: list[str] = Field(default_factory=list)


class ValidationIssue(BaseModel):
    """Validation finding with severity and context."""

    severity: str
    code: str
    message: str
    path: str | None = None


class ValidationReport(BaseModel):
    """Aggregate report generated by validator."""

    passed: bool
    errors: list[ValidationIssue] = Field(default_factory=list)
    warnings: list[ValidationIssue] = Field(default_factory=list)
    stats: dict[str, int] = Field(default_factory=dict)


class RetrievalHit(BaseModel):
    """Single retrieval hit for QA and agent tool use."""

    concept_id: str
    score: float
    content: str
    source_path: str
    metadata: dict[str, str] = Field(default_factory=dict)


class AgentAnswer(BaseModel):
    """Final response contract returned by query/agent surfaces."""

    answer: str
    citations: list[str] = Field(default_factory=list)
    used_concepts: list[str] = Field(default_factory=list)
    confidence: float = 0.0
    abstained: bool = False


class DiffChange(BaseModel):
    """Single OKF diff record between two bundle versions."""

    change_type: str
    concept_id: str
    old_path: str | None = None
    new_path: str | None = None
    details: str | None = None


class DiffReport(BaseModel):
    """Structured bundle diff output."""

    added: list[DiffChange] = Field(default_factory=list)
    removed: list[DiffChange] = Field(default_factory=list)
    modified: list[DiffChange] = Field(default_factory=list)
    renamed: list[DiffChange] = Field(default_factory=list)
    changed_metrics: list[DiffChange] = Field(default_factory=list)
    renamed_apis: list[DiffChange] = Field(default_factory=list)


class QAExample(BaseModel):
    """Gold QA evaluation sample."""

    example_id: str
    question: str
    expected_concepts: list[str] = Field(default_factory=list)
    reference_answer: str | None = None


class LLMJudgeScore(BaseModel):
    """LLM-as-judge scoring result."""

    faithfulness: float | None = None
    helpfulness: float | None = None
    completeness: float | None = None
    verdict: str = "unknown"
    reason: str = ""


class EvaluationResultItem(BaseModel):
    """Per-example evaluation output."""

    example_id: str
    question: str
    expected_concepts: list[str] = Field(default_factory=list)
    retrieved_concepts: list[str] = Field(default_factory=list)
    citations: list[str] = Field(default_factory=list)
    answer: str
    recall_at_k: float
    reciprocal_rank: float
    judge: LLMJudgeScore | None = None


class EvaluationSummary(BaseModel):
    """Aggregate evaluation summary."""

    total_examples: int
    avg_recall_at_k: float
    avg_mrr: float
    citation_coverage: float
    avg_faithfulness: float | None = None
    avg_helpfulness: float | None = None
    avg_completeness: float | None = None
    pass_rate: float | None = None


class EvaluationReport(BaseModel):
    """Structured report for QA evaluation runs."""

    mode: str
    top_k: int
    dataset_path: str
    generated_at: str
    summary: EvaluationSummary
    items: list[EvaluationResultItem]
